//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeatEquationSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeatEquationSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2*t.
        /// </summary>
        internal static string d2u_dx2 {
            get {
                return ResourceManager.GetString("d2u_dx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2*u.
        /// </summary>
        internal static string dK_du {
            get {
                return ResourceManager.GetString("dK_du", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x*x+6*x*t.
        /// </summary>
        internal static string du_dt {
            get {
                return ResourceManager.GetString("du_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2*x*t+3*t*t.
        /// </summary>
        internal static string du_dx {
            get {
                return ResourceManager.GetString("du_dx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x*x+6*x*t-2*u*Math.Pow(2*x*t+3*t*t,2)-2*t*K.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string InitCond {
            get {
                return ResourceManager.GetString("InitCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x*x*t+u*u.
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string LeftBoundCond {
            get {
                return ResourceManager.GetString("LeftBoundCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t+3*t*t.
        /// </summary>
        internal static string RightBoundCond {
            get {
                return ResourceManager.GetString("RightBoundCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x*x*t+3*x*t*t.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
    }
}
